doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        # server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            CMS:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/cms/entity'
                prefix: 'App\CMS\Domain\Entity'
                alias: CMS
            Security:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/security/entity'
                prefix: 'App\Security\Domain\Entity'
                alias: Security
