extensions:
    Memio\SpecGen\MemioSpecGenExtension: ~

suites:
    page:
        namespace: Front\Component\Page
        psr4_prefix: Front\Component\Page
        src_path: src/Front/Component/Page
        spec_path: src/Front/Component/Page
