front:
    resource: ../../src/UI/Front/Action/
    type: annotation

admin:
    resource: ../../src/UI/Admin/Action/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
