front:
    resource: ../../src/App/UI/Front/Controller/**/Action
    type: annotation

admin:
    resource: ../../src/App/UI/Admin/Controller/**/Action
    type: annotation

kernel:
    resource: ../../src/App/Kernel.php
    type: annotation
