front:
    resource: ../../src/UI/Front/Controller/**/Action
    type: annotation

admin:
    resource: ../../src/UI/Admin/Controller/**/Action
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
