index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'front/static/index.html.twig'
        context:
            name: "akawaka"
