stages:
  - test
  - deploy

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"

pages:
  image: ruby:2.7
  stage: deploy
  script:
    - ./configure --env=prod --clean-before-tasks
    - bundle install
    - bundle exec jekyll build -d public --config _config.yml,_config_prod.yml
  artifacts:
    paths:
      - public
  only:
    - main

assets:
  image: node:12-buster-slim
  stage: deploy
  script:
    - npm install
    - npm run build
    #- npx prettier --parser html --write ./public/*.html
  artifacts:
    paths:
      - public
    expire_in: 1 day
  needs:
    - job: pages
      artifacts: true

test:
  image: ruby:2.7
  stage: deploy
  script:
    - ./configure --env=prod --clean-before-tasks
    - bundle install
    - bundle exec jekyll build -d public --config _config.yml
    - mv ./build ./public
  artifacts:
    paths:
      - public
  needs:
    - job: assets
      artifacts: true
  except:
    - main
