admin_index:
    path: /
    controller: App\UI\Admin\Controller\Index\Action
    methods: ['GET']

admin_login:
    path: /login
    controller: App\UI\Admin\Controller\Login\Action
    methods: ['GET', 'POST']

admin_logout:
    path: /logout
    methods: ['GET']
