admin_cms_index:
    path: /
    controller: App\UI\Admin\Controller\CMS\Index\Action
    methods: ['GET']

admin_cms_channels:
    prefix: /channels
    resource: 'cms/channel.yaml'

admin_cms_pages:
    prefix: /pages
    resource: 'cms/page.yaml'

admin_cms_categories:
    prefix: /categories
    resource: 'cms/categories.yaml'

admin_cms_articles:
    prefix: /articles
    resource: 'cms/articles.yaml'
