admin_categories_index:
    path: /
    controller: App\UI\Admin\Controller\CMS\Category\List\Action
    methods: ['GET']

admin_categories_create:
    path: /new
    controller: App\UI\Admin\Controller\CMS\Category\Create\Action
    methods: ['GET', 'POST']

admin_categories_update:
    path: /{identifier}/update
    controller: App\UI\Admin\Controller\CMS\Category\Update\Action
    methods: ['GET', 'POST']

admin_categories_delete:
    path: /{identifier}/delete
    controller: App\UI\Admin\Controller\CMS\Category\Delete\Action
    methods: ['GET']
